language: android

# To use Travis Container-Based Infrastructure
sudo: false

cache:
  directories:
   - $HOME/.gradle/caches/

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.2
    - android-21
    - extra-google-google_play_services
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - echo no | android create avd --force -n testAvd -t android-21 --abi armeabi-v7a --skin WXGA800
  - emulator -avd testAvd -no-audio -no-window &

before_script:
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

deploy:
  provider: releases
  api_key:
    secure: Si6dy+ETFBwsbbjMOd9WI8ho0TMDnL46/vhKxLc5Rlvh75UUZH/ThEht/eRhZBP4IgEyg1oeR/8NOL8Lg70aA/cnv0c1+3u050MrUgDIMbbVwgo/l1v7CXfHvRYmicwcn5l9+qhcVaS3Lp7rftfeEvUgXLwwPS0kRxHZuINIYw8=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/App/build/outputs/apk/lokki-v*-debug.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: TheSoftwareFactory/lokki-android

notifications:
  slack:
    secure: eV5cEvPOZnp8ZK20CEI+0jt9VUxbtWpJJiSmo17C8TgL4MO5j0rjIBiDOMJhVExMEHxF9AZBCvXNEm1sozNv2VEt755QSPwqA6DTRswKmVQ1LWCOko4UWi3RF8rfSKPTPxAe5JM7Scm6SJQ8aQSIeXD6R8kw4nH6DbzuL/icqv0=
  email: false
